### ISSUE TITLE
Weapons with alt ammo reload incorrectly

### ISSUE THREAD

**Issue by piber20** [ZeOperator/Advanced-Tacticality#12]
Reloading a weapon that has alternate ammo will force both main and alt ammo to be reloaded. This can result in the main/alt loaded ammo exceeding the maximum clip size.

**Comment by ZeOperator** [comment]
This bug also relates to the Ammo interruption bug.

**Comment by piber20** [comment]
Should be fixed with my recent commit that rewrote the Player::ReloadWeapon function, but that may have introduced other bugs and missing reload-related features. Watch for anything weird.

**Comment by ZeOperator** [comment]
Bug fixed as of V1.0.9.
