### ISSUE TITLE
Fix error in Advanced Guns Akimbo not firing, loading and executing correctly.

### ISSUE THREAD

**Issue by ZeOperator** [ZeOperator/Advanced-Tacticality#3]
Has infinite ammo and doesnt reload at all. Ammo counter does not work correctly.

**Comment by piber20** [comment]
akimbo stuff should be fully working as of #9

**Comment by ZeOperator** [comment]
Needs lowering of time switching between states. Firing seems really choppy and god-awful. 

Fixable.
